import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Footer from '@/components/footer'
import Header from '@/components/header'

import { Providers } from './providers/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR" className="antialiased">
      <body className={inter.className}>
        <div className="flex h-full flex-col">
          <Providers>
            <Header />
            <div className="flex-1">{children}</div>
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  )
}
